### ISSUE TITLE
Link to model weights

### ISSUE THREAD

**Issue by Rusteam** [HRanWang/Spatial-Re-Scaling#5]
Hi,

would you mind sharing your model weights on other cloud where no registration is required?

I tried hard but can't make it work.

thanx

**Comment by RaviShivam** [comment]
Same issue here. I seem to get an error when I try to download the weights provided in [this link](https://pan.baidu.com/share/init?surl=mQkjrJMa1KQmaHax1kAjsw) using the provided password: 1ri5. 

Many thanks in advance.

**Comment by phamtrongthang123** [comment]
I downloaded and uploaded it on google drive [link](https://drive.google.com/file/d/14SRElnSeWrbvVsgFOI7gNHmwy6-Da5tW/view?usp=sharing). Hope it helps when waiting for official link from the author.

**Comment by Rusteam** [comment]
what architecture is used? There are differences in parameter names

**Comment by Rusteam** [comment]
all right I just loaded as he did in main.py.

Thanks @phamtrongthang123
